application: review-viz
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: helloworld_api.APPLICATION

- url: /css
  static_dir: css
  
- url: /css3
  static_dir: css3
- url: /js
  static_dir: js
  
- url: /data
  static_dir: data
  
- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts

- url: /templates
  static_dir: templates

#
- url: /.*
  script: review-viz.application
  #static_dir: /
  
libraries:
- name: pycrypto
  version: latest
  
- name: endpoints
  version: 1.0